"""OpenType feature metadata: human-readable labels and HarfBuzz default state.

The authoritative list of features actually present in a font comes from its
GSUB/GPOS tables (see :mod:`backend.app.font_info`).  The tables here only
provide display names and the list of feature tags HarfBuzz turns on by
default for the generic shaper, so the UI can show a meaningful initial state
of each toggle.
"""

# Feature tags HarfBuzz enables by default.  rlig is enabled by every shaper;
# the rest are the default set for the generic/horizontal shaper, plus the
# vertical-direction defaults.  They only take effect when the font actually
# provides the feature for the active script/language (checked separately).
DEFAULT_ON_TAGS = frozenset(
    [
        "calt",
        "ccmp",
        "clig",
        "dist",
        "kern",
        "liga",
        "locl",
        "mark",
        "mkmk",
        "rlig",
        # vertical writing defaults
        "vkrn",
        "vmark",
        "vmkm",
        "vhaln",
        "halt",
        "vpal",
    ]
)

# Short labels for common registered OpenType feature tags.  Unknown tags are
# displayed as their raw 4-character tag.
FEATURE_LABELS = {
    "aalt": "Access All Alternates",
    "abvf": "Above-base Forms",
    "abvm": "Above-base Mark Positioning",
    "abvs": "Above-base Substitutions",
    "afrc": "Alternative Fractions",
    "akhn": "Akhands",
    "blwf": "Below-base Forms",
    "blwm": "Below-base Mark Positioning",
    "blws": "Below-base Substitutions",
    "calt": "Contextual Alternates",
    "case": "Case-Sensitive Forms",
    "ccmp": "Glyph Composition / Decomposition",
    "cfar": "Conjunct Form After Ro",
    "chws": "Contextual Half-width Spacing",
    "cjct": "Conjunct Forms",
    "clig": "Contextual Ligatures",
    "cpct": "Centered CJK Punctuation",
    "cpsp": "Capital Spacing",
    "cswh": "Contextual Swash",
    "curs": "Cursive Positioning",
    "cv01": "Character Variant 1",
    "cv02": "Character Variant 2",
    "cv03": "Character Variant 3",
    "cv04": "Character Variant 4",
    "cv05": "Character Variant 5",
    "c2pc": "Petite Capitals From Capitals",
    "c2sc": "Small Capitals From Capitals",
    "dist": "Distances",
    "dlig": "Discretionary Ligatures",
    "dnom": "Denominators",
    "dtls": "Dotless Forms",
    "expt": "Expert Forms",
    "falt": "Final Glyph on Line Alternates",
    "fin2": "Terminal Forms #2",
    "fin3": "Terminal Forms #3",
    "fina": "Terminal Forms",
    "flac": "Flattened Accent Forms",
    "frac": "Fractions",
    "fwid": "Full Widths",
    "half": "Half Forms",
    "haln": "Halant Forms",
    "halt": "Alternate Half Widths",
    "hist": "Historical Forms",
    "hkna": "Horizontal Kana Alternates",
    "hlig": "Historical Ligatures",
    "hngl": "Hangul",
    "hojo": "Hojo Kanji Forms",
    "hwid": "Half Widths",
    "init": "Initial Forms",
    "isol": "Isolated Forms",
    "ital": "Italics",
    "jalt": "Justification Alternates",
    "jp04": "JIS2004 Forms",
    "jp78": "JIS78 Forms",
    "jp83": "JIS83 Forms",
    "jp90": "JIS90 Forms",
    "kern": "Kerning",
    "lfbd": "Left Bounds",
    "liga": "Standard Ligatures",
    "ljmo": "Leading Jamo Forms",
    "lnum": "Lining Figures",
    "locl": "Localized Forms",
    "ltra": "Left-to-right alternates",
    "ltrm": "Left-to-right mirrored forms",
    "mark": "Mark Positioning",
    "med2": "Medial Forms #2",
    "medi": "Medial Forms",
    "mgrk": "Mathematical Greek",
    "mkmk": "Mark to Mark Positioning",
    "mset": "Mark Positioning via Substitution",
    "nalt": "Alternate Annotation Forms",
    "nlck": "NLC Kanji Forms",
    "nukt": "Nukta Forms",
    "numr": "Numerators",
    "onum": "Oldstyle Figures",
    "opbd": "Optical Bounds",
    "ordn": "Ordinals",
    "ornm": "Ornaments",
    "palt": "Proportional Alternate Widths",
    "pcap": "Petite Capitals",
    "pkna": "Proportional Kana",
    "pnum": "Proportional Figures",
    "pref": "Pre-base Forms",
    "pres": "Pre-base Substitutions",
    "pstf": "Post-base Forms",
    "psts": "Post-base Substitutions",
    "pwid": "Proportional Widths",
    "qwid": "Quarter Widths",
    "rand": "Randomize",
    "rclt": "Required Contextual Alternates",
    "rkrf": "Rakar Forms",
    "rlig": "Required Ligatures",
    "rphf": "Reph Forms",
    "rtbd": "Right Bounds",
    "rtla": "Right-to-left alternates",
    "rtlm": "Right-to-left mirrored forms",
    "ruby": "Ruby Notation Forms",
    "salt": "Stylistic Alternates",
    "sinf": "Scientific Inferiors",
    "size": "Optical Size",
    "smcp": "Small Capitals",
    "smpl": "Simplified Forms",
    "ss01": "Stylistic Set 1",
    "ss02": "Stylistic Set 2",
    "ss03": "Stylistic Set 3",
    "ss04": "Stylistic Set 4",
    "ss05": "Stylistic Set 5",
    "ss06": "Stylistic Set 6",
    "ss07": "Stylistic Set 7",
    "ss08": "Stylistic Set 8",
    "ss09": "Stylistic Set 9",
    "ss10": "Stylistic Set 10",
    "ss11": "Stylistic Set 11",
    "ss12": "Stylistic Set 12",
    "ss13": "Stylistic Set 13",
    "ss14": "Stylistic Set 14",
    "ss15": "Stylistic Set 15",
    "ss16": "Stylistic Set 16",
    "ss17": "Stylistic Set 17",
    "ss18": "Stylistic Set 18",
    "ss19": "Stylistic Set 19",
    "ss20": "Stylistic Set 20",
    "ssty": "Script Style Forms",
    "stch": "Stretching Glyph Decomposition",
    "subs": "Subscript",
    "sups": "Superscript",
    "swsh": "Swash",
    "titl": "Titling",
    "tjmo": "Trailing Jamo Forms",
    "tnam": "Traditional Name Forms",
    "tnum": "Tabular Figures",
    "trad": "Traditional Forms",
    "twid": "Third Widths",
    "unic": "Unicase",
    "valt": "Alternate Vertical Metrics",
    "vatu": "Vattu Variants",
    "vchw": "Vertical Contextual Half-width Spacing",
    "vert": "Vertical Writing",
    "vhal": "Alternate Vertical Half Metrics",
    "vjmo": "Vowel Jamo Forms",
    "vkna": "Vertical Kana Alternates",
    "vkrn": "Vertical Kerning",
    "vpalf": "Vertical Proportional Alternate Lining Figures",
    "vpalt": "Vertical Proportional Alternate Metrics",
    "vpal": "Vertical Proportional Alternate Widths",
    "vrt2": "Vertical Alternates and Rotation",
    "zero": "Slashed Zero",
}


def feature_label(tag: str) -> str:
    return FEATURE_LABELS.get(tag, tag)
