/** Short Chinese descriptions for common OpenType feature tags. */
const LABELS: Record<string, string> = {
  liga: '标准连字',
  clig: '上下文连字',
  rlig: '必需连字',
  calt: '上下文替代',
  kern: '字偶距',
  mark: '记号定位',
  mkmk: '记号间定位',
  curs: '草书连接',
  ccmp: '组合与分解',
  locl: '本地化字形',
  fina: '词尾形式',
  init: '词首形式',
  medi: '词中形式',
  isol: '独立形式',
  rtlm: 'RTL 镜像',
  liga2: '罕见连字',
  dlig: '自由连字',
  hlig: '历史连字',
  smcp: '小型大写',
  c2sc: '大写转小型大写',
  onum: '老式数字',
  lnum: '线性数字',
  pnum: '比例数字',
  tnum: '表格数字',
  sups: '上标',
  subs: '下标',
  numr: '分子',
  dnom: '分母',
  frac: '分式',
  zero: '带斜杠的零',
  ss01: '风格集 1',
  ss02: '风格集 2',
  ss03: '风格集 3',
  ss04: '风格集 4',
  ss05: '风格集 5',
  ss06: '风格集 6',
  ss07: '风格集 7',
  ss08: '风格集 8',
  ss09: '风格集 9',
  ss10: '风格集 10',
  cv01: '字符变体 1',
  cv02: '字符变体 2',
  cv03: '字符变体 3',
  aalt: '全部替代',
  salt: '风格替代',
  swsh: '花笔',
  hist: '历史形式',
  dist: '距离定位',
  abvm: '上方记号',
  blwm: '下方记号',
  vrt2: '垂直替换',
  vert: '垂直写法',
  vpal: '垂直比例字距',
  vkna: '垂直假名'
}

export function featureLabel(tag: string): string {
  return LABELS[tag] ?? tag
}
